services:
  console:
    container_name: redpanda-console
    image: docker.redpanda.com/redpandadata/console:latest
    entrypoint: /bin/sh
    command: -c 'echo "$$CONSOLE_CONFIG_FILE" > /tmp/config.yml; /app/console'
    environment:
      CONFIG_FILEPATH: /tmp/config.yml
      CONSOLE_CONFIG_FILE: |
        kafka:
          brokers:
            - ""
            - ""
            - ""
          
          sasl:
            enabled: true
            mechanism: SCRAM-SHA-512
            username: username
            password: password

          tls:
            enabled: true
    ports:
      - 8080:8080
   
networks:
  iceberg_net:

