-- ===========================================================================================================
-- -- require("dapui").setup({
--
--   icons = {
--     expanded = "⯆",
--     collapsed = "⯈",
--     circular = "↺"
--   },
--   mappings = {
--     -- Use a table to apply multiple mappings
--     expand = {"<CR>", "<2-LeftMouse>"},
--     open = "o",
--     remove = "d",
--     edit = "e",
--   },
--   sidebar = {
--     elements = {
--       -- You can change the order of elements in the sidebar
--       "scopes",
--       "stacks",
--       "watches"
--     },
--     width = 40,
--     position = "left" -- Can be "left" or "right"
--   },
--   tray = {
--     elements = {
--       "repl"
--     },
--     height = 10,
--     position = "bottom" -- Can be "bottom" or "top"
--   },
--   floating = {
--     max_height = nil, -- These can be integers or a float between 0 and 1.
--     max_width = nil   -- Floats will be treated as percentage of your screen.
--   }
-- })
--
-- local dap = require"dap"
--
-- dap.adapters.go = {
--   type = 'executable';
--   command = 'node';
--   args = {os.getenv('HOME') .. '/Projects/softwares/vscode-go'};
-- }
-- dap.configurations.go = {
--   {
--     type = 'go';
--     name = 'Debug';
--     request = 'launch';
--     showLog = false;
--     program = "${file}";
--     dlvToolPath = vim.fn.exepath('dlv')  -- Adjust to where delve is installed
--   },
-- }
-- ===========================================================================================================
-- replace fidget.nvim: https://www.reddit.com/r/neovim/comments/1scg235/comment/oedgldy/
-- vim.api.nvim_create_autocmd('LspProgress', {
--   group = group,
--   desc = 'show lsp progress messages in ui2',
--   callback = function(ev)
--     local value = ev.data.params.value
--     vim.api.nvim_echo({ { value.message or 'done' } }, false, {
--       id = 'lsp.' .. ev.data.client_id,
--       kind = 'progress',
--       source = 'vim.lsp',
--       title = value.title,
--       status = value.kind ~= 'end' and 'running' or 'success',
--       percent = value.percentage,
--     })
--   end,
-- })
-- ===========================================================================================================
-- -- Neovim only sometimes prints `recording @` when recording macros with cmdheight=0.
-- -- So leave a manual message to indicate recording indeed has started.
--
-- vim.api.nvim_create_autocmd("RecordingEnter", {
--     group = group,
--     callback = function()
--         vim.api.nvim_echo({{"recording macro"}}, false, {})
--     end,
-- })
--
-- vim.api.nvim_create_autocmd("RecordingLeave", {
--     group = group,
--     callback = function()
--         vim.api.nvim_echo({{"done recording macro"}}, false, {})
--     end,
-- })
-- ===========================================================================================================
