require("fenil.telescope")
require("fenil.harpoon")
require("fenil.play")
require("fenil.lsp")
require("fenil.lsp-trouble")
require("fenil.lualine")
require("fenil.compe")
require("fenil.treesitter")
require("fenil.rust-tools")
require("fenil.symbolsoutline")
-- require("fenil.nvim-autopairs")
-- require("fenil.autosession")
-- require("fenil.whichkey")
-- require("fenil.rainbow")

-- require('spellsitter').setup()
-- require("fenil.whid")
