require("fenil.lualine")
require("fenil.telescope")
require("fenil.harpoon")
require("fenil.treesitter")
require("fenil.lsp")
require("fenil.cmp")
require("fenil.nvim-autopairs")
-- require("fenil.tabout")
require("fenil.lsp-trouble")
require("fenil.symbolsoutline")
require("fenil.rust-tools")
require("fenil.play")
require("fenil.lightbulb")
require("fenil.fidget")

-- require("fenil.whid")
