-- require'rust-tools.hover_range'.hover_range()

-- local capabilities = require "fenil.cmp".capabilities
-- local on_attach = require "fenil.lsp".on_attach

-- require('rust-tools').setup {
--     server = {
--         cmd = { "rustup", "run", "nightly", "rust-analyzer" },
--         on_attach = on_attach,
--         capabilities = capabilities,
--         settings = {
--             -- to enable rust-analyzer settings visit:
--             -- https://github.com/rust-analyzer/rust-analyzer/blob/master/docs/user/generated_config.adoc
--             ["rust-analyzer"] = {
--                 -- enable clippy on save
--                 checkOnSave = {
--                     command = "clippy"
--                 },
--             },
--         },
--     }
-- }
